# --- Site settings ---
title: "Haridhanush Ravichandran"
email: "haridhanush.ravi@gmail.com"
description: >-
  MS in Data Science @ UNIPD | Interested in Deep Learning, NLP, Knowledge Representation and Learning
baseurl: "" 
url: "https://haridhanush-ravichandran.github.io" 
github_username: Haridhanush-Ravichandran
linkedin_username: haridhanush-ravichandran

# --- Personal info ---
author:
  name: "Haridhanush Ravichandran"
  email: "haridhanush.ravi@gmail.com"
  github: "https://github.com/haridhanush-ravichandran"
  linkedin: "https://linkedin.com/in/haridhanush-ravichandran"

# --- Navbar links ---
navbar-links:
  About Me: "aboutme"
  Projects:
    - "Kaggle CNN Classifier": "projects/kaggle-cnn"
    - "Sales & Customer Dashboard": "projects/sales-dashboard"
    - "HR Dashboard": "projects/hr-dashboard"
  CV: "assets/Haridhanush_Ravichandran_CV.pdf"
  Contact: "mailto:haridhanush.ravi@gmail.com"

# --- SEO & social ---
social-network-links:
  github: haridhanush-ravichandran
  linkedin: haridhanush-ravichandran
  email: haridhanush.ravi@gmail.com

# --- Footer options ---
footer-links-active:
  linkedin: true
  github: true
  email: true

# --- Build settings ---
markdown: kramdown
theme: beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
