# --- Site settings ---
title: "Haridhanush Ravichandran"
email: "haridhanush.ravi@gmail.com"
description: >-
  MS in Data Science @ UNIPD | Interested in Deep Learning, NLP, Knowledge Representation and Learning.
baseurl: "" 
url: "https://haridhanush-ravichandran.github.io" 
github_username: Haridhanush-Ravichandran
linkedin_username: haridhanush-ravichandran

# --- Personal info ---
author:
  name: "Haridhanush Ravichandran"
  email: "haridhanush.ravi@gmail.com"
  github: "https://github.com/haridhanush-ravichandran"
  linkedin: "https://linkedin.com/in/haridhanush-ravichandran"

# --- Navbar links ---
navbar-links:
  About Me: "aboutme"
  Projects: "projects"
  CV: "cv"
  Contact: "contact"

# --- SEO & social ---
social-network-links:
  github: haridhanush-ravichandran
  linkedin: haridhanush-ravichandran
  email: haridhanush.ravi@gmail.com

# --- Footer options ---
footer-links-active:
  linkedin: true
  github: true
  email: true

# --- Build settings ---
markdown: kramdown
remote_theme: daattali/beautiful-jekyll@master
plugins:
  - jekyll-feed
  - jekyll-seo-tag
custom-css: "assets/css/custom.css"
